### PR TITLE
chore: integrate part of DDE packages

### PR DESCRIPTION
**Pull request by zsien**
相关 Tag 原始 PR：

* https://github.com/linuxdeepin/dde-daemon/pull/492
* https://github.com/linuxdeepin/startdde/pull/216
* https://github.com/linuxdeepin/dde-application-manager/pull/16
* https://github.com/linuxdeepin/deepin-fcitx5configtool-plugin/pull/21

注意，此集成需要等待 dtk 的集成进行完毕后才能顺利进行。相关集成 PR：

* https://github.com/deepin-community/Repository-Integration/pull/60
* https://github.com/deepin-community/Repository-Integration/pull/58

### CODE REVIEW

**Comment by zsien** [comment]
看起来缺了依赖 golang-github-mdlayher-netlink-dev

**Comment by Zeno-sole** [comment]
> 看起来缺了依赖 golang-github-mdlayher-netlink-dev

缺少 golang-github-mdlayher-netlink 等我先吧这个集成后在更新吧

**Comment by Zeno-sole** [comment]
> > 看起来缺了依赖 golang-github-mdlayher-netlink-dev
> 
> 缺少 golang-github-mdlayher-netlink 等我先吧这个集成后在更新吧

已补充 但是依然构建失败  https://build.deepin.com/package/show/deepin:CI:TestingIntegration:test-intergration-pr-67/dde-daemon

**Comment by zsien** [comment]
> > > 看起来缺了依赖 golang-github-mdlayher-netlink-dev
> > 
> > 
> > 缺少 golang-github-mdlayher-netlink 等我先吧这个集成后在更新吧
> 
> 已补充 但是依然构建失败 https://build.deepin.com/package/show/deepin:CI:TestingIntegration:test-intergration-pr-67/dde-daemon

得等下 https://github.com/deepin-community/Repository-Integration/pull/58 了。。。

**Comment by Zeno-sole** [comment]
> > > > 看起来缺了依赖 golang-github-mdlayher-netlink-dev
> > > 
> > > 
> > > 缺少 golang-github-mdlayher-netlink 等我先吧这个集成后在更新吧
> > 
> > 
> > 已补充 但是依然构建失败 https://build.deepin.com/package/show/deepin:CI:TestingIntegration:test-intergration-pr-67/dde-daemon
> 
> 得等下 #58 了。。。

58没问题的话可以走测试验证了。不过得等到下载测完了

**Comment by 18202781743** [comment]
这波集成的时候把这个也带上吧，https://github.com/linuxdeepin/developer-center/issues/3690，它是linuxdeepin/deepin-fcitx5configtool-plugin的

**Comment by zsien** [comment]
放入 https://github.com/deepin-community/Repository-Integration/pull/58 一起提交

**Pull request closed without merging**
